### ISSUE TITLE
New model for checking permissions

### ISSUE THREAD

**Issue by michaelsevilla** [systemslab/infra#3]
Need to decide if we ant everything to be run as root, because we run into a bunch of permissions problems.

**Comment by ivotron** [comment]
Every time we launch an sshd-based container, we can provide the public ssh key to inject to the `.ssh/known_hosts` file, so we could add an ansible variable that holds this info and passes it to the container at `docker run`-time. Would this work?

**Comment by ivotron** [comment]
I guess I'm confused about what you mean with "run as root"

**Comment by michaelsevilla** [comment]
This was just a note to myself. It doesn't have to do with anything your wrote in [cephdev](https://github.com/ivotron/docker-cephdev) -- all that works fine.

I have Ansible in a container and it orchestrates the cluster according to what's in `hosts`. If I create a file in the container (`touch /tmp/docker/file.txt`) it has root permissions. So if I try to delete without the container, then I get a permissions error.

**Comment by ivotron** [comment]
Oh, i see. Yeah, that's an issue that I haven't found how to solve. Seems that an "official" solution is planned for 1.11 https://github.com/docker/docker/issues/7198

**Comment by michaelsevilla** [comment]
Fixed with experiment slave (i.e. "eslave") functionality in commit 5735c46.
